### ISSUE TITLE
Date Formate from PostgreSQL to Java

### ISSUE THREAD

**Issue by omardbaa** [n4j1Br4ch1D/simplon-java-issues#2]
To fixed that problem
instead of create code like this 

String sql = "INSERT INTO Task (Title, Description , Status, Deadline, Category) VALUES (?, ?, ?, ?,? )";

**Comment by n4j1Br4ch1D** [comment]
?::Date

**Comment by Elon-Fask** [comment]
Wonderful

**Comment by omardbaa** [comment]
Now the code be like th
is

String sql = "INSERT INTO Task (Title, Description , Status, Deadline, Category) VALUES (?, ?, ?, ?::Date,? )";
