### ISSUE TITLE
Loading FXML document with JavaFX API

### ISSUE THREAD

**Issue by elon-fask** [n4j1Br4ch1D/simplon-java-issues#3]
after running my code i face this error
```
Jun 20, 2022 5:52:28 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 18 by JavaFX runtime of version 13
```

**Comment by elon-fask** [comment]
i think it's from the version that my JavaFX use the moment of running?!!!

**Comment by n4j1Br4ch1D** [comment]
maybe try diffrent config 
https://www.dummies.com/article/technology/programming-web-design/java/how-to-configure-java-in-eclipse-150777/
